version: '3.8'

services:
  ai-art-platform:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-comprehensive-art-platform-secret}
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./art_platform.db:/app/art_platform.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-art-platform
    restart: unless-stopped